#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : AVBStreamHandler
Version  : 1.0.3
Release  : 14
URL      : https://github.com/intel/AVBStreamHandler/releases/download/v1.0.3/AVBStreamHandler-v1.0.3.tar.gz
Source0  : https://github.com/intel/AVBStreamHandler/releases/download/v1.0.3/AVBStreamHandler-v1.0.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: AVBStreamHandler-bin = %{version}-%{release}
Requires: AVBStreamHandler-data = %{version}-%{release}
Requires: AVBStreamHandler-lib = %{version}-%{release}
Requires: AVBStreamHandler-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : googletest-dev
BuildRequires : libcap-bin
BuildRequires : libcap-dev
BuildRequires : pciutils-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(automotive-dlt)
BuildRequires : pkgconfig(automotive-dlt-c++)
BuildRequires : pkgconfig(sndfile)
BuildRequires : sudo
BuildRequires : systemd-dev
BuildRequires : tbb-dev
BuildRequires : zlib-dev

%description
INTRODUCTION
This component demonstrates various features of the Intel I210 Ethernet
controller. These features can be used for developing Audio/Video Bridging
applications, Industrial Ethernet applications which require precise timing
control over frame transmission, or test harnesses for measuring system
latencies and sampling events.

%package bin
Summary: bin components for the AVBStreamHandler package.
Group: Binaries
Requires: AVBStreamHandler-data = %{version}-%{release}
Requires: AVBStreamHandler-license = %{version}-%{release}

%description bin
bin components for the AVBStreamHandler package.


%package data
Summary: data components for the AVBStreamHandler package.
Group: Data

%description data
data components for the AVBStreamHandler package.


%package dev
Summary: dev components for the AVBStreamHandler package.
Group: Development
Requires: AVBStreamHandler-lib = %{version}-%{release}
Requires: AVBStreamHandler-bin = %{version}-%{release}
Requires: AVBStreamHandler-data = %{version}-%{release}
Provides: AVBStreamHandler-devel = %{version}-%{release}

%description dev
dev components for the AVBStreamHandler package.


%package lib
Summary: lib components for the AVBStreamHandler package.
Group: Libraries
Requires: AVBStreamHandler-data = %{version}-%{release}
Requires: AVBStreamHandler-license = %{version}-%{release}

%description lib
lib components for the AVBStreamHandler package.


%package license
Summary: license components for the AVBStreamHandler package.
Group: Default

%description license
license components for the AVBStreamHandler package.


%prep
%setup -q -n AVBStreamHandler

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544121071
mkdir -p clr-build
pushd clr-build
%cmake .. -DIAS_IS_HOST_BUILD=1 -DIAS_DISABLE_DOC=1 -DCMAKE_INSTALL_LIBDIR=lib64
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1544121071
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/AVBStreamHandler
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/AVBStreamHandler/LICENSE.txt
cp deps/audio/common/LICENSE.txt %{buildroot}/usr/share/package-licenses/AVBStreamHandler/deps_audio_common_LICENSE.txt
cp deps/igb_avb/kmod/COPYING %{buildroot}/usr/share/package-licenses/AVBStreamHandler/deps_igb_avb_kmod_COPYING
cp deps/igb_avb/kmod/LICENSE %{buildroot}/usr/share/package-licenses/AVBStreamHandler/deps_igb_avb_kmod_LICENSE
cp deps/igb_avb/lib/LICENSE %{buildroot}/usr/share/package-licenses/AVBStreamHandler/deps_igb_avb_lib_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
%exclude /usr/lib64/ias-audio-common/asound_module_pcm_smartx.cmake
%exclude /usr/lib64/ias-audio-common/asound_module_rate_smartx.cmake
%exclude /usr/lib64/ias-audio-common/ias-audio-common.cmake

%files bin
%defattr(-,root,root,-)
/usr/bin/avb_streamhandler_demo
/usr/bin/daemon_cl

%files data
%defattr(-,root,root,-)
/usr/share/alsa/alsa.conf.d/50-smartx.conf

%files dev
%defattr(-,root,root,-)
%exclude /usr/lib64/libias-audio-common.so
/usr/include/audio/common/IasAudioCommonTypes.hpp
/usr/include/audio/common/audiobuffer/IasMemoryAllocator.hpp
/usr/include/audio/common/audiobuffer/IasMetaData.hpp
/usr/include/audio/common/audiobuffer/IasMetaDataFactory.hpp
/usr/include/audio/common/audiobuffer/IasUserMetaDataFactory.hpp
/usr/include/internal/audio/common/IasAlsaTypeConversion.hpp
/usr/include/internal/audio/common/IasAudioLogging.hpp
/usr/include/internal/audio/common/IasCommonVersion.hpp
/usr/include/internal/audio/common/IasDataProbe.hpp
/usr/include/internal/audio/common/IasDataProbeHelper.hpp
/usr/include/internal/audio/common/IasFdSignal.hpp
/usr/include/internal/audio/common/IasIntProcCondVar.hpp
/usr/include/internal/audio/common/IasIntProcMutex.hpp
/usr/include/internal/audio/common/alsa_smartx_plugin/IasAlsaHwConstraintsDynamic.hpp
/usr/include/internal/audio/common/alsa_smartx_plugin/IasAlsaHwConstraintsStatic.hpp
/usr/include/internal/audio/common/alsa_smartx_plugin/IasAlsaPluginIpc.hpp
/usr/include/internal/audio/common/alsa_smartx_plugin/IasAlsaPluginShmConnection.hpp
/usr/include/internal/audio/common/alsa_smartx_plugin/IasSmartXPluginIpcStructures.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioIpc.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioIpcMessageContainer.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioIpcProtocolHead.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioIpcProtocolMacro.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioIpcProtocolTail.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioRingBuffer.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioRingBufferFactory.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioRingBufferMirror.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioRingBufferReal.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioRingBufferResult.hpp
/usr/include/internal/audio/common/audiobuffer/IasAudioRingBufferTypes.hpp
/usr/include/internal/audio/common/helper/IasCopyAudioAreaBuffers.hpp
/usr/include/internal/audio/common/helper/IasIRunnable.hpp
/usr/include/internal/audio/common/helper/IasThread.hpp
/usr/include/internal/audio/common/samplerateconverter/IasSrcController.hpp
/usr/include/internal/audio/common/samplerateconverter/IasSrcFarrow.hpp
/usr/include/internal/audio/common/samplerateconverter/IasSrcWrapper.hpp
/usr/include/internal/audio/common/samplerateconverter/IasSrcWrapperBase.hpp
/usr/lib64/ias-audio-common/asound_module_pcm_smartx.cmake
/usr/lib64/ias-audio-common/asound_module_rate_smartx.cmake
/usr/lib64/ias-audio-common/ias-audio-common.cmake
/usr/lib64/libias-media_transport-avb_streamhandler.so
/usr/lib64/pluginias-media_transport-avb_configuration_reference.so

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/alsa-lib/libasound_module_pcm_smartx.so
%exclude /usr/lib64/alsa-lib/libasound_module_rate_smartx.so
%exclude /usr/lib64/libias-audio-common.so.4
%exclude /usr/lib64/libias-audio-common.so.4.0.0
/usr/lib64/libias-media_transport-avb_streamhandler.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/AVBStreamHandler/LICENSE.txt
/usr/share/package-licenses/AVBStreamHandler/deps_audio_common_LICENSE.txt
/usr/share/package-licenses/AVBStreamHandler/deps_igb_avb_kmod_COPYING
/usr/share/package-licenses/AVBStreamHandler/deps_igb_avb_kmod_LICENSE
/usr/share/package-licenses/AVBStreamHandler/deps_igb_avb_lib_LICENSE
